---
title: "scholar.with.year"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
scholar_url_year <- function (query, num_pages = 1, ano.inicio, ano.fim) 
{
  num_pages <- seq(0, num_pages - 1) * 10

scholar_url <- paste0("https://scholar.google.com/scholar?start=", num_pages, "&q=",'"',            stringr::str_replace_all(query, " ", "+"), '"',
       "&hl=pt-BR&as_sdt=0,5&as_ylo=", ano.inicio,
       "&as_yhi=", ano.fim
       
       )

scholar_url
}

#n <- scholar_url_year(query = "esporte olímpico", num_pages = 2, ano.inicio = 2014, ano.fim = 2016)
```



```{r}
scholar_df_one_page_year <- function (scholar_url_year) 
{
    library(dplyr)
    message("Getting page ", scholar_url_year)
    Sys.sleep(5)
    
    scholar_html <- rvest::read_html(scholar_url_year)
    
    titles <- scholar_html %>% rvest::html_nodes(".gs_rt") %>% 
        rvest::html_text() %>% stringr::str_remove_all("\\[.*\\]") %>% 
        stringr::str_trim()
    
    authors_years <- scholar_html %>% rvest::html_nodes(".gs_a") %>% 
        rvest::html_text()
    
    authors <- stringr::str_remove(authors_years, "\\s-\\s.*")
    years <- stringr::str_extract(authors_years, "\\d{4}")
    
    journal <- stringr::str_extract(authors_years, "\\s-\\s.*\\s-\\s|\\s-\\s.*") %>% 
        stringr::str_remove_all("\\s-\\s")
    
    citation <- scholar_html %>% rvest::html_nodes(".gs_fl a") %>% 
        rvest::html_text() %>% dplyr::as_tibble() %>% dplyr::rename(citation = value) %>% 
        dplyr::mutate(citation = dplyr::if_else(stringr::str_detect(citation, 
            "Citar"), dplyr::lead(citation), NULL)) %>% 
        stats::na.omit() %>% dplyr::mutate(citation = dplyr::if_else(stringr::str_detect(citation, 
        "Citado"), as.numeric(stringr::str_remove(citation, 
        "Citado por ")), 0))
  
      article_id_link <- dplyr::tibble(article_id = scholar_html %>% 
        rvest::html_nodes(".gs_rt a") %>% rvest::html_attr("id"), 
        article_link = scholar_html %>% rvest::html_nodes(".gs_rt a") %>% 
            rvest::html_attr("href"))
    
      article_id <- scholar_html %>% rvest::html_nodes(".gs_or") %>% 
        rvest::html_attr("data-cid") %>% dplyr::as_tibble() %>% 
        dplyr::rename(article_id = value)
    links <- dplyr::left_join(article_id, article_id_link, by = "article_id") %>% 
        dplyr::select(article_link)
    
    dplyr::tibble(titulo = titles, autores = authors, ano = years, 
        revista = journal, citacao = citation$citation, link = links$article_link)
}
```

Test
```{r}
df <- scholar_df_one_page_year(n[1])
```

```{r}
scholar_df_year <- 
function (query, num_pages = 1, ano.inicio, ano.fim) 
{
    scholar_urls_year <- scholar_url_year(query = query, num_pages = num_pages, ano.inicio = ano.inicio, ano.fim = ano.fim)
    do.call("rbind", lapply(scholar_urls_year, scholar_df_one_page_year))
}
```


```{r}
teste.anos <- scholar_df_year(query = "esporte olímpico", 
                                 num_pages = 2, 
                                 ano.inicio = 2014, 
                                 ano.fim = 2016)
```

